"""
TITAN XAU AI — Trend Strategy Engine (Module 6)
Production implementation: 5 entry patterns, R-multiple management,
adaptive position sizing, EMA-based trend following.
"""
from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional

import numpy as np

from titan.regime.engine import Regime, RegimeFeatures

logger = logging.getLogger(__name__)


class TrendPattern(str, Enum):
    HH_HL = "HH_HL"              # Higher Highs / Higher Lows (uptrend)
    LH_LL = "LH_LL"              # Lower Highs / Lower Lows (downtrend)
    BREAKOUT = "BREAKOUT"        # Range breakout
    PULLBACK = "PULLBACK"        # Pullback to EMA in trend
    CONTINUATION = "CONTINUATION" # Trend continuation after consolidation


class SignalDirection(int, Enum):
    LONG = 1
    SHORT = -1
    FLAT = 0


@dataclass
class TrendSignal:
    """Signal generated by trend strategy."""
    direction: SignalDirection
    pattern: TrendPattern
    entry_price: float
    stop_loss: float
    take_profit: float
    risk_reward_ratio: float
    confidence: float
    proposed_volume: float
    r_multiple: float = 1.0       # Risk multiple for this trade
    timestamp: float = field(default_factory=time.time)


class TrendStrategyEngine:
    """
    Trend Following Strategy with 5 entry patterns.
    Uses EMA crossover, ADX, HH/HL patterns, breakout, pullback.
    R-multiple position management (1R risk, 2R+ reward).
    """

    def __init__(self, config: dict = None):
        cfg = config or {}
        self._ema_fast = cfg.get("ema_fast", 20)
        self._ema_slow = cfg.get("ema_slow", 50)
        self._adx_threshold = cfg.get("adx_threshold", 25)
        self._atr_period = cfg.get("atr_period", 14)
        self._default_rr = cfg.get("risk_reward", 2.0)
        self._min_confidence = cfg.get("min_confidence", 0.65)
        self._risk_per_trade = cfg.get("risk_per_trade", 0.01)  # 1% equity
        self._signal_count = 0
        self._win_count = 0

    def generate_signal(
        self,
        closes: np.ndarray,
        highs: np.ndarray,
        lows: np.ndarray,
        features: RegimeFeatures,
        current_price: float,
        account_equity: float,
    ) -> Optional[TrendSignal]:
        """Generate trend signal based on 5 patterns."""
        if len(closes) < self._ema_slow + 10:
            return None

        # Only trade in TREND regime
        # (regime check is done by caller, but we double-check features)

        # Compute EMAs
        ema_fast = self._compute_ema(closes, self._ema_fast)
        ema_slow = self._compute_ema(closes, self._ema_slow)

        # ATR for stop placement
        atr = self._compute_atr(highs, lows, closes, self._atr_period)
        if atr <= 0:
            return None

        # Check each pattern
        patterns = [
            self._check_hh_hl(highs, lows, closes, ema_fast, ema_slow, atr, features, current_price),
            self._check_lh_ll(highs, lows, closes, ema_fast, ema_slow, atr, features, current_price),
            self._check_breakout(highs, lows, closes, atr, features, current_price),
            self._check_pullback(closes, ema_fast, ema_slow, atr, features, current_price),
            self._check_continuation(closes, ema_fast, ema_slow, atr, features, current_price),
        ]

        # Select highest-confidence pattern
        valid_signals = [s for s in patterns if s is not None and s.confidence >= self._min_confidence]
        if not valid_signals:
            return None

        best = max(valid_signals, key=lambda s: s.confidence)

        # Adaptive position sizing based on confidence
        best.proposed_volume = self._calculate_volume(
            account_equity, current_price, best.stop_loss, best.confidence
        )

        self._signal_count += 1
        logger.info(
            f"Trend signal: {best.direction.name} {best.pattern.value} "
            f"conf={best.confidence:.2f} R={best.risk_reward_ratio:.1f}"
        )
        return best

    def _check_hh_hl(self, highs, lows, closes, ema_f, ema_s, atr, features, price):
        """Pattern 1: Higher Highs / Higher Lows — uptrend continuation."""
        if not features.hh_hl_pattern:
            return None
        if ema_f[-1] <= ema_s[-1]:  # EMA fast must be above slow
            return None
        if features.adx < self._adx_threshold:
            return None

        direction = SignalDirection.LONG
        stop_loss = price - 1.5 * atr
        take_profit = price + (self._default_rr * 1.5 * atr)
        rr = (take_profit - price) / (price - stop_loss) if (price - stop_loss) > 0 else 0

        confidence = min(0.5 + features.adx / 100, 0.95)

        return TrendSignal(
            direction=direction, pattern=TrendPattern.HH_HL,
            entry_price=price, stop_loss=stop_loss, take_profit=take_profit,
            risk_reward_ratio=rr, confidence=confidence,
            proposed_volume=0.0, r_multiple=self._default_rr,
        )

    def _check_lh_ll(self, highs, lows, closes, ema_f, ema_s, atr, features, price):
        """Pattern 2: Lower Highs / Lower Lows — downtrend continuation."""
        if not features.lh_ll_pattern:
            return None
        if ema_f[-1] >= ema_s[-1]:  # EMA fast must be below slow
            return None
        if features.adx < self._adx_threshold:
            return None

        direction = SignalDirection.SHORT
        stop_loss = price + 1.5 * atr
        take_profit = price - (self._default_rr * 1.5 * atr)
        rr = (price - take_profit) / (stop_loss - price) if (stop_loss - price) > 0 else 0

        confidence = min(0.5 + features.adx / 100, 0.95)

        return TrendSignal(
            direction=direction, pattern=TrendPattern.LH_LL,
            entry_price=price, stop_loss=stop_loss, take_profit=take_profit,
            risk_reward_ratio=rr, confidence=confidence,
            proposed_volume=0.0, r_multiple=self._default_rr,
        )

    def _check_breakout(self, highs, lows, closes, atr, features, price):
        """Pattern 3: Range breakout — price breaks 20-bar high/low."""
        if len(highs) < 20:
            return None
        recent_high = np.max(highs[-20:])
        recent_low = np.min(lows[-20:])

        if price > recent_high and features.adx > 20:
            direction = SignalDirection.LONG
            stop_loss = recent_low
            take_profit = price + (self._default_rr * (price - stop_loss))
            rr = self._default_rr
            confidence = min(0.6 + features.volume_ratio / 10, 0.90)
        elif price < recent_low and features.adx > 20:
            direction = SignalDirection.SHORT
            stop_loss = recent_high
            take_profit = price - (self._default_rr * (stop_loss - price))
            rr = self._default_rr
            confidence = min(0.6 + features.volume_ratio / 10, 0.90)
        else:
            return None

        return TrendSignal(
            direction=direction, pattern=TrendPattern.BREAKOUT,
            entry_price=price, stop_loss=stop_loss, take_profit=take_profit,
            risk_reward_ratio=rr, confidence=confidence,
            proposed_volume=0.0, r_multiple=self._default_rr,
        )

    def _check_pullback(self, closes, ema_f, ema_s, atr, features, price):
        """Pattern 4: Pullback to EMA in established trend."""
        if features.adx < self._adx_threshold:
            return None

        # Uptrend pullback: price near EMA fast from above
        if ema_f[-1] > ema_s[-1] and features.price_above_ema:
            distance = abs(price - ema_f[-1])
            if distance < 0.5 * atr and features.rsi > 40:
                direction = SignalDirection.LONG
                stop_loss = price - 1.0 * atr
                take_profit = price + (self._default_rr * 1.0 * atr)
                rr = self._default_rr
                confidence = min(0.55 + features.adx / 100, 0.85)
                return TrendSignal(
                    direction=direction, pattern=TrendPattern.PULLBACK,
                    entry_price=price, stop_loss=stop_loss, take_profit=take_profit,
                    risk_reward_ratio=rr, confidence=confidence,
                    proposed_volume=0.0, r_multiple=self._default_rr,
                )

        # Downtrend pullback
        if ema_f[-1] < ema_s[-1] and not features.price_above_ema:
            distance = abs(price - ema_f[-1])
            if distance < 0.5 * atr and features.rsi < 60:
                direction = SignalDirection.SHORT
                stop_loss = price + 1.0 * atr
                take_profit = price - (self._default_rr * 1.0 * atr)
                rr = self._default_rr
                confidence = min(0.55 + features.adx / 100, 0.85)
                return TrendSignal(
                    direction=direction, pattern=TrendPattern.PULLBACK,
                    entry_price=price, stop_loss=stop_loss, take_profit=take_profit,
                    risk_reward_ratio=rr, confidence=confidence,
                    proposed_volume=0.0, r_multiple=self._default_rr,
                )

        return None

    def _check_continuation(self, closes, ema_f, ema_s, atr, features, price):
        """Pattern 5: Continuation after consolidation in trend direction."""
        if features.adx < self._adx_threshold:
            return None

        # Check for consolidation followed by expansion
        if len(closes) < 10:
            return None

        # Use closes range as proxy (highs/lows not passed to this method)
        recent_closes = closes[-5:]
        prev_closes = closes[-10:-5]

        avg_recent = float(np.max(recent_closes) - np.min(recent_closes))
        avg_prev = float(np.max(prev_closes) - np.min(prev_closes))

        if avg_prev == 0:
            return None

        # Consolidation ending: recent range > 1.5x previous
        if avg_recent > 1.5 * avg_prev:
            if ema_f[-1] > ema_s[-1] and features.price_above_ema:
                direction = SignalDirection.LONG
                stop_loss = price - 1.5 * atr
                take_profit = price + (self._default_rr * 1.5 * atr)
                confidence = 0.70
            elif ema_f[-1] < ema_s[-1] and not features.price_above_ema:
                direction = SignalDirection.SHORT
                stop_loss = price + 1.5 * atr
                take_profit = price - (self._default_rr * 1.5 * atr)
                confidence = 0.70
            else:
                return None

            rr = self._default_rr
            return TrendSignal(
                direction=direction, pattern=TrendPattern.CONTINUATION,
                entry_price=price, stop_loss=stop_loss, take_profit=take_profit,
                risk_reward_ratio=rr, confidence=confidence,
                proposed_volume=0.0, r_multiple=self._default_rr,
            )

        return None

    def _calculate_volume(self, equity, entry, stop, confidence):
        """Adaptive position sizing based on confidence and risk."""
        risk_amount = equity * self._risk_per_trade
        risk_per_lot = abs(entry - stop) * 100  # 100 oz per lot for XAUUSD
        if risk_per_lot <= 0:
            return 0.01

        base_volume = risk_amount / risk_per_lot
        # Scale by confidence (0.5-1.0x multiplier)
        confidence_mult = 0.5 + (confidence - self._min_confidence) / (1.0 - self._min_confidence) * 0.5
        volume = base_volume * confidence_mult
        return max(round(volume, 2), 0.01)

    @staticmethod
    def _compute_ema(data, period):
        alpha = 2.0 / (period + 1)
        ema = np.zeros(len(data))
        ema[0] = data[0]
        for i in range(1, len(data)):
            ema[i] = alpha * data[i] + (1 - alpha) * ema[i-1]
        return ema

    @staticmethod
    def _compute_atr(highs, lows, closes, period=14):
        tr = np.maximum(
            highs - lows,
            np.maximum(
                np.abs(highs - np.roll(closes, 1)),
                np.abs(lows - np.roll(closes, 1)),
            ),
        )
        tr[0] = highs[0] - lows[0]
        return float(np.mean(tr[-period:])) if len(tr) >= period else 1.0

    @property
    def stats(self):
        return {"signals": self._signal_count, "wins": self._win_count}
